winget install --id=ScooterSoftware.BeyondCompare4 -e && 
winget install --id=Git.Git -e && 
winget install --id=GitHub.cli -e && 
winget install --id=Microsoft.GitCredentialManagerCore -e && 
winget install --id=Microsoft.PowerShell -e && 
winget install --id=Microsoft.WindowsTerminal -e && 
winget install --id=Kitware.CMake -e && 
winget install --id=Microsoft.VisualStudio.2022.Professional -e && 
winget install --id=Microsoft.VisualStudioCode -e && 
winget install --id=AgileBits.1Password -e && 
winget install --id=AgileBits.1Password.CLI -e && 
winget install --id=Canonical.Ubuntu.2204 -e
